language: php
php:
  - 7.0
  - 7.1

before_script:
  - composer install --dev --no-interaction --prefer-source
  - nvm use v6.9.2

script:
  - composer lint
  - composer test
  - npm i
  - npm run lint
  - npm run test
