language: php
php:
  - 7.0
  - 7.1

node_js:
  - 'lts/*'

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - composer lint
  - composer test
  - npm i
  - npm run lint
  - npm run test
